name: PackRat
main: src.PackRat
version: 1.0
api-version: 1.19
author: rleboeu
description: This plugin allows players to choose which items they pickup.
commands:
  packrat:
    description: Manage item pickup blacklist.
    usage: /<command> [nopickup/pickup/clear/show] [item/hand]
    default: true