name: Packrat
main: src.Packrat
version: 1.0
api-version: 1.19
author: rleboeu
description: Packrat allows players to choose which items they loot.
commands:
  nopickup:
    description: Disable looting for an item.
    usage: /<command> [ITEM_NAME:hand:all]
  pickup:
    description: Enable looting for an item, or list currently blocked pickups.
    usage: /<command> [ITEM_NAME:hand:all:list]